apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pers-pv-claim
  namespace: xenon-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: redis-pers-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pers-pv
  namespace: xenon-app
  labels:
    type: redis-pers-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/redis/redis-pers-test"
    server: 10.X.X.X
    readOnly: false
